export const FETCH_TOP_GAMES_PENDING = 'FETCH_TOP_GAMES_PENDING';
export const FETCH_TOP_GAMES_SUCCESS = 'FETCH_TOP_GAMES_SUCCESS';
export const FETCH_TOP_GAMES_ERROR = 'FETCH_TOP_GAMES_ERROR';

export const FETCH_GAME_STREAMS_PENDING = 'FETCH_GAME_STREAMS_PENDING';
export const FETCH_GAME_STREAMS_SUCCESS = 'FETCH_GAME_STREAMS_SUCCESS';
export const FETCH_GAME_STREAMS_ERROR = 'FETCH_GAME_STREAMS_ERROR';

export const SET_GAME_NAME = 'SET_GAME_NAME';
export const CHANGE_SELETED_STREAM = 'CHANGE_SELETED_STREAM';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
