export const FETCH_TOP_GAMES = 'FETCH_TOP_GAMES';
export const FETCH_GAME_STREAMS = 'FETCH_GAME_STREAMS';
export const CHANGE_SELETED_STREAM = 'CHANGE_SELETED_STREAM';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
